"""tabela nova +coluna

Revision ID: 0148b0abd71e
Revises: 516158cf4803
Create Date: 2025-07-19 14:50:03.372010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0148b0abd71e'
down_revision = '516158cf4803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placastatus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placa_a_caminho', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placastatus', schema=None) as batch_op:
        batch_op.drop_column('placa_a_caminho')

    # ### end Alembic commands ###
