"""tabela nova -col

Revision ID: 516158cf4803
Revises: cd794399c611
Create Date: 2025-07-19 14:49:03.929310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516158cf4803'
down_revision = 'cd794399c611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placastatus', schema=None) as batch_op:
        batch_op.drop_column('placa_a_caminho')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placastatus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placa_a_caminho', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
