"""tabela nova

Revision ID: cd794399c611
Revises: 54f93558fd50
Create Date: 2025-07-19 14:46:22.299942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd794399c611'
down_revision = '54f93558fd50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placastatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=80), nullable=False),
    sa.Column('placa_confeccionada', sa.Boolean(), nullable=True),
    sa.Column('placa_a_caminho', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placastatus')
    # ### end Alembic commands ###
