"""Initial migration.

Revision ID: da7291ea2f2d
Revises: 0148b0abd71e
Create Date: 2025-07-19 18:48:19.435715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7291ea2f2d'
down_revision = '0148b0abd71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placastatus')
    with op.batch_alter_table('placa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placa_confeccionada', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('placa_a_caminho', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placa', schema=None) as batch_op:
        batch_op.drop_column('placa_a_caminho')
        batch_op.drop_column('placa_confeccionada')

    op.create_table('placastatus',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('placa', sa.VARCHAR(length=80), nullable=False),
    sa.Column('placa_confeccionada', sa.BOOLEAN(), nullable=True),
    sa.Column('placa_a_caminho', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
